### ISSUE TITLE
Publish reference lat, lon, alt

### ISSUE THREAD

**Issue by mmmfarrell** [superjax/inertial_sense#1]
It'd be useful to have the ros node also publish the reference lat, lon, alt that it uses to calculate your position in meters. And maybe even be able to set the reference lat, lon, alt with a service call.

**Comment by superjax** [comment]
I guess that is all in the "flash configuration"  I don't think it'll be too hard to get this working.

**Comment by superjax** [comment]
This was added in the latest commit.
