### ISSUE TITLE
Can't manually set GPS_ref_lla

### ISSUE THREAD

**Issue by dallinbriggs** [superjax/inertial_sense#6]
Setting the GPS_ref_lla doesn't seem to change the position in the /ins message. It will change the z position, but x and y remain the same.

**Comment by dallinbriggs** [comment]
Actually, it appears that the GPS_ref_lla should not be converted into radians in lines 66 and 67 of inertial_sense.cpp.

**Comment by superjax** [comment]
Oh, yeah.  That was a bug in the version of the SDK that I used originally.  Thanks for figuring that out!

**Comment by superjax** [comment]
Is this solved?

**Comment by mmmfarrell** [comment]
Fixed with PR #7 Thanks @dallinbriggs
